@extends('layouts.admin')

@section('title', 'Search Sources')

@section('breadcrumb')
<a href="/admin">Dashboard</a> <span class="sep">›</span>
<a href="/admin/search">Search</a> <span class="sep">›</span>
<span>Sources</span>
@endsection

@section('page_title', 'Search Sources')
@section('page_actions')
<div style="display:flex;align-items:center;gap:.75rem">
  <a href="/admin/search" class="btn btn--ghost btn--sm">
    <i data-lucide="arrow-left" class="w-4 h-4"></i> Back to Search
  </a>
  <p class="text-sm text-muted" style="margin:0">Configure which entities and fields are included in search results</p>
</div>
@endsection

@section('content')
<div class="admin-content" style="padding:1.5rem">

  {{-- Flash Messages --}}
  @if(!empty($success))
  <div class="alert alert--success" style="margin-bottom:1.5rem">
    <strong>✓</strong> {{ $success }}
  </div>
  @endif

  <form method="POST" action="/admin/search/sources" class="sources-form" id="sources-form">
    <input type="hidden" name="_csrf" value="{{ $cms['csrf_token'] ?? '' }}">

    <div class="sources-grid">
      @foreach($sources as $key => $source)
      <div class="source-card {{ $source->enabled ? 'source-card--enabled' : 'source-card--disabled' }}"
           id="source-{{ $key }}" data-source="{{ $key }}">

        {{-- Card Header --}}
        <div class="source-card__header">
          <label class="source-card__toggle">
            <input type="checkbox"
              name="sources[{{ $key }}][enabled]"
              value="1"
              class="source-toggle"
              data-source="{{ $key }}"
              {{ $source->enabled ? 'checked' : '' }}>
            <span class="source-card__switch"></span>
          </label>
          <div class="source-card__info">
            <h3 class="source-card__title">
              @if($source->icon)
              <i data-lucide="{{ $source->icon }}" class="w-4 h-4"></i>
              @endif
              {{ $source->label }}
            </h3>
            <span class="source-card__badge">{{ $source->table }}</span>
          </div>
          <input type="hidden" name="sources[{{ $key }}][priority]" value="{{ $source->priority }}">
        </div>

        {{-- URL Pattern --}}
        <div class="source-card__row">
          <label class="source-card__label">URL Pattern</label>
          <input type="text" class="form-input form-input--sm"
            name="sources[{{ $key }}][url_pattern]"
            value="{{ $source->urlPattern }}"
            placeholder="/{slug}">
        </div>

        {{-- Search Fields (dynamic checkboxes from real DB columns) --}}
        <div class="source-card__row">
          <label class="source-card__label">Search Fields <span style="font-weight:400;color:#475569">(select columns to index)</span></label>
          <div class="source-card__fields" id="fields-{{ $key }}">
            @foreach($columns[$key] ?? [] as $col)
            @php
              $isText = in_array($col, ['title','name','body','summary','description','alt','email','original_name','slug','content','text','bio','notes','label','meta_title','meta_description','excerpt']);
              $isChecked = in_array($col, $source->searchFields);
              $isSystem = in_array($col, ['id','created_at','updated_at','deleted_at','password']);
            @endphp
            @if(!$isSystem)
            <label class="source-card__field-toggle {{ $isText ? 'source-card__field-toggle--text' : '' }}">
              <input type="checkbox"
                name="sources[{{ $key }}][search_fields][]"
                value="{{ $col }}"
                class="field-checkbox"
                data-source="{{ $key }}"
                data-field="{{ $col }}"
                {{ $isChecked ? 'checked' : '' }}>
              <span class="source-card__field-name">{{ $col }}</span>
            </label>
            @endif
            @endforeach
          </div>
        </div>

        {{-- Field Weights (dynamic — generated by JS based on checked fields) --}}
        <div class="source-card__row">
          <label class="source-card__label">Field Weights <span style="font-weight:400;color:#475569">(boost relevance per field)</span></label>
          <div class="source-card__weights" id="weights-{{ $key }}">
            {{-- Populated dynamically by JS --}}
          </div>
        </div>

        {{-- Title & Summary Fields --}}
        <div class="source-card__row source-card__row--grid">
          <div>
            <label class="source-card__label">Title Field</label>
            <select name="sources[{{ $key }}][title_field]" class="form-select form-select--sm">
              @foreach($columns[$key] ?? [] as $col)
              <option value="{{ $col }}" {{ $source->titleField === $col ? 'selected' : '' }}>{{ $col }}</option>
              @endforeach
            </select>
          </div>
          <div>
            <label class="source-card__label">Summary Field</label>
            <select name="sources[{{ $key }}][summary_field]" class="form-select form-select--sm">
              <option value="">— None —</option>
              @foreach($columns[$key] ?? [] as $col)
              <option value="{{ $col }}" {{ $source->summaryField === $col ? 'selected' : '' }}>{{ $col }}</option>
              @endforeach
            </select>
          </div>
        </div>

        {{-- Status & Soft Delete --}}
        <div class="source-card__row source-card__row--grid">
          <div>
            <label class="source-card__label">Status Field</label>
            <select name="sources[{{ $key }}][status_field]" class="form-select form-select--sm">
              <option value="">— None —</option>
              @foreach($columns[$key] ?? [] as $col)
              <option value="{{ $col }}" {{ $source->statusField === $col ? 'selected' : '' }}>{{ $col }}</option>
              @endforeach
            </select>
          </div>
          <div>
            <label class="source-card__label">Required Status</label>
            <input type="text" class="form-input form-input--sm"
              name="sources[{{ $key }}][status_value]"
              value="{{ $source->statusValue ?? '' }}"
              placeholder="e.g. published">
          </div>
        </div>

        {{-- Date & Entity Type --}}
        <div class="source-card__row source-card__row--grid">
          <div>
            <label class="source-card__label">Date Field</label>
            <select name="sources[{{ $key }}][date_field]" class="form-select form-select--sm">
              <option value="">— None —</option>
              @foreach($columns[$key] ?? [] as $col)
              <option value="{{ $col }}" {{ $source->dateField === $col ? 'selected' : '' }}>{{ $col }}</option>
              @endforeach
            </select>
          </div>
          <div>
            <label class="source-card__label">Entity Type Label</label>
            <input type="text" class="form-input form-input--sm"
              name="sources[{{ $key }}][entity_type]"
              value="{{ $source->entityType }}"
              placeholder="e.g. content">
          </div>
        </div>

        {{-- Stats Footer --}}
        <div class="source-card__footer">
          <span class="source-card__stat">
            <strong>{{ $counts[$key] ?? 0 }}</strong> records
          </span>
          <span class="source-card__stat source-card__field-count" id="field-count-{{ $key }}">
            {{ count($source->searchFields) }} fields indexed
          </span>
        </div>

      </div>
      @endforeach
    </div>

    <div class="sources-actions">
      <button type="submit" class="btn btn--primary">
        <i data-lucide="save" class="w-4 h-4"></i>
        Save Source Configuration
      </button>
    </div>
  </form>

  {{-- ── Content Type Dynamic Fields ─────────────────────────────── --}}
  @if(!empty($contentTypeFields))
  <div style="margin-top:2.5rem">
    <h2 style="font-size:1.1rem;font-weight:700;color:#e2e8f0;margin-bottom:.25rem">
      <i data-lucide="layers" class="w-4 h-4" style="display:inline-block;vertical-align:middle;margin-right:.3rem"></i>
      Content Type Fields
    </h2>
    <p style="color:#64748b;font-size:.8rem;margin-bottom:1.25rem">
      Custom fields per content type. Toggle <strong style="color:#818cf8">searchable</strong> to include in search results.
      These are EAV fields stored in <code style="font-size:.7rem;background:rgba(255,255,255,.04);padding:.1rem .3rem;border-radius:3px">node_fields</code>.
    </p>

    <form method="POST" action="/admin/search/sources/fields" id="ct-fields-form">
      <input type="hidden" name="_csrf" value="{{ $cms['csrf_token'] ?? '' }}">

      <div class="ct-fields-grid">
        @foreach($contentTypeFields as $typeId => $ctData)
        <div class="ct-card">
          <div class="ct-card__header">
            <i data-lucide="file-type" class="w-4 h-4"></i>
            <span class="ct-card__title">{{ $ctData['label'] }}</span>
            <span class="ct-card__badge">{{ $typeId }}</span>
          </div>
          <div class="ct-card__body">
            @foreach($ctData['fields'] as $field)
            <div class="ct-field-row">
              <div class="ct-field-info">
                <span class="ct-field-name">{{ $field['machine_name'] }}</span>
                <span class="ct-field-label">{{ $field['label'] }}</span>
                <span class="ct-field-type">{{ $field['field_type'] }}</span>
              </div>
              <label class="source-card__toggle" style="width:36px;height:20px">
                <input type="checkbox"
                  name="fields[{{ $field['machine_name'] }}]"
                  value="1"
                  {{ $field['searchable'] ? 'checked' : '' }}>
                <span class="source-card__switch" style="border-radius:10px">
                </span>
              </label>
            </div>
            @endforeach
          </div>
        </div>
        @endforeach
      </div>

      <div class="sources-actions">
        <button type="submit" class="btn btn--primary">
          <i data-lucide="save" class="w-4 h-4"></i>
          Save Field Searchability
        </button>
      </div>
    </form>
  </div>
  @endif

</div>

@push('head')
<style>
  .sources-grid {
    display: grid;
    grid-template-columns: 1fr;
    gap: 1.25rem;
  }

  .source-card {
    background: var(--admin-card-bg, rgba(255,255,255,.03));
    border: 1px solid var(--admin-border, rgba(255,255,255,.08));
    border-radius: 14px;
    overflow: hidden;
    transition: border-color .2s, opacity .2s;
  }

  .source-card--enabled {
    border-color: rgba(129, 140, 248, .2);
  }

  .source-card--disabled {
    opacity: .55;
  }

  .source-card__header {
    display: flex;
    align-items: center;
    gap: .75rem;
    padding: 1rem 1.25rem;
    border-bottom: 1px solid rgba(255,255,255,.04);
    background: rgba(255,255,255,.02);
  }

  /* Toggle Switch */
  .source-card__toggle {
    position: relative;
    width: 40px;
    height: 22px;
    flex-shrink: 0;
  }

  .source-card__toggle input { opacity: 0; width: 0; height: 0; position: absolute; }

  .source-card__switch {
    position: absolute;
    inset: 0;
    border-radius: 11px;
    background: rgba(255,255,255,.08);
    cursor: pointer;
    transition: background .2s;
  }

  .source-card__switch::before {
    content: '';
    position: absolute;
    top: 3px;
    left: 3px;
    width: 16px;
    height: 16px;
    border-radius: 50%;
    background: #64748b;
    transition: transform .2s, background .2s;
  }

  .source-card__toggle input:checked + .source-card__switch {
    background: rgba(129, 140, 248, .3);
  }

  .source-card__toggle input:checked + .source-card__switch::before {
    transform: translateX(18px);
    background: #818cf8;
  }

  .source-card__info { flex: 1; min-width: 0; }

  .source-card__title {
    display: flex;
    align-items: center;
    gap: .4rem;
    font-size: .92rem;
    font-weight: 600;
    color: var(--admin-text, #e2e8f0);
    margin: 0;
  }

  .source-card__badge {
    display: inline-block;
    padding: .1rem .4rem;
    border-radius: 4px;
    background: rgba(255,255,255,.04);
    color: #64748b;
    font-size: .65rem;
    font-family: 'JetBrains Mono', monospace;
    margin-top: .2rem;
  }

  .source-card__row {
    padding: .75rem 1.25rem;
    border-bottom: 1px solid rgba(255,255,255,.03);
  }

  .source-card__row--grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: .75rem;
  }

  .source-card__label {
    display: block;
    font-size: .7rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: .04em;
    color: #64748b;
    margin-bottom: .4rem;
  }

  /* Field Checkboxes */
  .source-card__fields {
    display: flex;
    flex-wrap: wrap;
    gap: .3rem;
  }

  .source-card__field-toggle {
    display: inline-flex;
    align-items: center;
    gap: .3rem;
    padding: .2rem .5rem;
    border-radius: 6px;
    border: 1px solid rgba(255,255,255,.06);
    font-size: .7rem;
    color: #64748b;
    cursor: pointer;
    transition: all .15s;
    user-select: none;
  }

  .source-card__field-toggle--text {
    border-color: rgba(129, 140, 248, .12);
  }

  .source-card__field-toggle:has(input:checked) {
    background: rgba(129, 140, 248, .12);
    border-color: rgba(129, 140, 248, .3);
    color: #818cf8;
  }

  .source-card__field-toggle input { display: none; }

  .source-card__field-name {
    font-family: 'JetBrains Mono', monospace;
    font-size: .65rem;
  }

  /* Dynamic Weights */
  .source-card__weights {
    display: flex;
    flex-wrap: wrap;
    gap: .5rem;
    min-height: 30px;
  }

  .source-card__weight-item {
    display: inline-flex;
    align-items: center;
    gap: .35rem;
    padding: .2rem .5rem;
    background: rgba(255,255,255,.02);
    border: 1px solid rgba(255,255,255,.05);
    border-radius: 6px;
    animation: weightFadeIn .2s ease;
  }

  @keyframes weightFadeIn {
    from { opacity: 0; transform: scale(.95); }
    to { opacity: 1; transform: scale(1); }
  }

  .source-card__weight-label {
    font-size: .68rem;
    color: #94a3b8;
    font-family: 'JetBrains Mono', monospace;
  }

  .source-card__weight-input {
    width: 55px;
    padding: .15rem .3rem;
    border-radius: 4px;
    border: 1px solid rgba(255,255,255,.08);
    background: rgba(0,0,0,.3);
    color: #e2e8f0;
    font-size: .7rem;
    font-family: 'JetBrains Mono', monospace;
    text-align: center;
  }

  .source-card__weights-empty {
    font-size: .7rem;
    color: #475569;
    font-style: italic;
  }

  /* Footer */
  .source-card__footer {
    display: flex;
    justify-content: space-between;
    padding: .6rem 1.25rem;
    background: rgba(0,0,0,.15);
    font-size: .7rem;
    color: #475569;
  }

  .source-card__stat strong { color: #818cf8; }

  .sources-actions {
    margin-top: 1.5rem;
    display: flex;
    justify-content: flex-end;
  }

  @media (max-width: 900px) {
    .sources-grid { grid-template-columns: 1fr; }
    .ct-fields-grid { grid-template-columns: 1fr; }
    .source-card__row--grid { grid-template-columns: 1fr; }
  }

  /* Content Type Field Cards */
  .ct-fields-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
    gap: 1rem;
  }

  .ct-card {
    background: rgba(255,255,255,.03);
    border: 1px solid rgba(255,255,255,.08);
    border-radius: 12px;
    overflow: hidden;
  }

  .ct-card__header {
    display: flex;
    align-items: center;
    gap: .5rem;
    padding: .75rem 1rem;
    border-bottom: 1px solid rgba(255,255,255,.04);
    background: rgba(255,255,255,.02);
  }

  .ct-card__title {
    font-size: .85rem;
    font-weight: 600;
    color: #e2e8f0;
  }

  .ct-card__badge {
    margin-left: auto;
    padding: .1rem .4rem;
    border-radius: 4px;
    background: rgba(255,255,255,.04);
    color: #64748b;
    font-size: .6rem;
    font-family: 'JetBrains Mono', monospace;
  }

  .ct-card__body { padding: .25rem 0; }

  .ct-field-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: .5rem 1rem;
    border-bottom: 1px solid rgba(255,255,255,.02);
    transition: background .15s;
  }

  .ct-field-row:hover {
    background: rgba(255,255,255,.02);
  }

  .ct-field-row:last-child { border-bottom: none; }

  .ct-field-info {
    display: flex;
    align-items: center;
    gap: .5rem;
    min-width: 0;
  }

  .ct-field-name {
    font-family: 'JetBrains Mono', monospace;
    font-size: .72rem;
    color: #c4b5fd;
    font-weight: 500;
  }

  .ct-field-label {
    font-size: .72rem;
    color: #94a3b8;
  }

  .ct-field-type {
    padding: .05rem .3rem;
    border-radius: 3px;
    background: rgba(255,255,255,.04);
    color: #475569;
    font-size: .58rem;
    font-family: 'JetBrains Mono', monospace;
  }
</style>
@endpush

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {

  // ── Initial weights data from PHP (field → weight) ─────────────
  const sourceWeights = {
    @foreach($sources as $key => $source)
    '{{ $key }}': {
      @foreach($source->fieldWeights as $f => $w)
      '{{ $f }}': {{ $w }},
      @endforeach
    },
    @endforeach
  };

  // ── Rebuild weights UI for a source ────────────────────────────
  function rebuildWeights(sourceKey) {
    const container = document.getElementById('weights-' + sourceKey);
    const checkboxes = document.querySelectorAll(
      `input.field-checkbox[data-source="${sourceKey}"]:checked`
    );

    if (checkboxes.length === 0) {
      container.innerHTML = '<span class="source-card__weights-empty">Select fields above to set weights</span>';
      updateFieldCount(sourceKey, 0);
      return;
    }

    let html = '';
    checkboxes.forEach(cb => {
      const field = cb.dataset.field;
      const weight = (sourceWeights[sourceKey] && sourceWeights[sourceKey][field]) || 1.0;
      html += `
        <div class="source-card__weight-item">
          <span class="source-card__weight-label">${field}</span>
          <input type="number" class="source-card__weight-input"
            name="sources[${sourceKey}][weights][${field}]"
            value="${weight}"
            min="0.1" max="10" step="0.1">
        </div>
      `;
    });
    container.innerHTML = html;
    updateFieldCount(sourceKey, checkboxes.length);

    // Update local state when weight changes
    container.querySelectorAll('.source-card__weight-input').forEach(input => {
      input.addEventListener('change', function() {
        const field = this.closest('.source-card__weight-item')
          .querySelector('.source-card__weight-label').textContent;
        if (!sourceWeights[sourceKey]) sourceWeights[sourceKey] = {};
        sourceWeights[sourceKey][field] = parseFloat(this.value) || 1.0;
      });
    });
  }

  function updateFieldCount(sourceKey, count) {
    const el = document.getElementById('field-count-' + sourceKey);
    if (el) el.textContent = count + ' field' + (count !== 1 ? 's' : '') + ' indexed';
  }

  // ── Toggle card enabled/disabled styling ───────────────────────
  document.querySelectorAll('.source-toggle').forEach(toggle => {
    toggle.addEventListener('change', function() {
      const card = document.getElementById('source-' + this.dataset.source);
      card.classList.toggle('source-card--enabled', this.checked);
      card.classList.toggle('source-card--disabled', !this.checked);
    });
  });

  // ── Field checkbox changes → rebuild weights ───────────────────
  document.querySelectorAll('.field-checkbox').forEach(cb => {
    cb.addEventListener('change', function() {
      rebuildWeights(this.dataset.source);
    });
  });

  // ── Initial build ──────────────────────────────────────────────
  const sourceKeys = [...new Set(
    [...document.querySelectorAll('.field-checkbox')].map(cb => cb.dataset.source)
  )];
  sourceKeys.forEach(key => rebuildWeights(key));

});
</script>
@endpush

@endsection
