<?php

declare(strict_types=1);

namespace App\Cms\Config;

/**
 * MlcWriter — Serializes PHP arrays to MLC (MonkeysLegion Config) format.
 *
 * Output format:
 *   block_type "identifier" {
 *       key = "value"
 *       key = true
 *       nested {
 *           key = "value"
 *       }
 *   }
 */
final class MlcWriter
{
    /**
     * Serialize a config block to MLC format.
     *
     * @param string $blockType   e.g. 'settings', 'content_type', 'vocabulary'
     * @param string $identifier  e.g. 'general', 'article', 'tags'
     * @param array  $data        Key-value config data
     */
    public static function serialize(string $blockType, string $identifier, array $data): string
    {
        $lines = [];
        $lines[] = "# Auto-generated by MonkeysCMS config:export";
        $lines[] = "# Exported: " . date('Y-m-d H:i:s T');
        $lines[] = "";
        $lines[] = "{$blockType} \"{$identifier}\" {";

        foreach ($data as $key => $value) {
            self::writeValue($lines, $key, $value, 1);
        }

        $lines[] = "}";
        $lines[] = "";

        return implode("\n", $lines);
    }

    /**
     * Serialize multiple blocks into a single MLC file.
     *
     * @param string $blockType
     * @param array<string, array> $items  Keyed by identifier
     */
    public static function serializeMany(string $blockType, array $items): string
    {
        $parts = [];
        foreach ($items as $id => $data) {
            $parts[] = self::serialize($blockType, $id, $data);
        }
        return implode("\n", $parts);
    }

    /**
     * Parse an MLC file into structured data.
     *
     * @return array<string, array<string, mixed>>  Keyed by block identifier
     */
    public static function parse(string $content): array
    {
        $result = [];
        $lines = explode("\n", $content);
        $stack = [];
        $current = null;
        $currentId = null;
        $depth = 0;
        $nestedKey = null;
        $nestedData = null;

        foreach ($lines as $line) {
            $trimmed = trim($line);

            // Skip comments and empty
            if ($trimmed === '' || str_starts_with($trimmed, '#')) {
                continue;
            }

            // Match: block_type "identifier" {
            if ($depth === 0 && preg_match('/^(\w+)\s+"([^"]+)"\s*\{/', $trimmed, $m)) {
                $currentId = $m[1] . ':' . $m[2];  // "settings:general"
                $current = ['_type' => $m[1], '_id' => $m[2]];
                $depth = 1;
                continue;
            }

            // Match: nested_key {
            if ($depth > 0 && preg_match('/^(\w+)\s*\{/', $trimmed, $m)) {
                $stack[] = [$nestedKey, $nestedData];
                $nestedKey = $m[1];
                $nestedData = [];
                $depth++;
                continue;
            }

            // Closing brace
            if ($trimmed === '}') {
                $depth--;
                if ($depth === 0 && $currentId !== null) {
                    $result[$currentId] = $current;
                    $current = null;
                    $currentId = null;
                } elseif ($depth >= 1 && $nestedKey !== null) {
                    $savedKey = $nestedKey;
                    $savedData = $nestedData;

                    if (!empty($stack)) {
                        [$nestedKey, $nestedData] = array_pop($stack);
                    } else {
                        $nestedKey = null;
                        $nestedData = null;
                    }

                    // Assign nested data to parent — handle repeated keys as list arrays
                    if ($nestedData !== null && $nestedKey !== null) {
                        if (isset($nestedData[$savedKey])) {
                            // Key already exists → convert to list or append
                            if (!is_array($nestedData[$savedKey]) || !array_is_list($nestedData[$savedKey]) || !is_array(($nestedData[$savedKey][0] ?? null))) {
                                $nestedData[$savedKey] = [$nestedData[$savedKey]];
                            }
                            $nestedData[$savedKey][] = $savedData;
                        } else {
                            $nestedData[$savedKey] = $savedData;
                        }
                    } elseif ($current !== null) {
                        if (isset($current[$savedKey])) {
                            // Repeated block at root level → collect into list
                            if (!is_array($current[$savedKey]) || !array_is_list($current[$savedKey]) || !is_array(($current[$savedKey][0] ?? null))) {
                                $current[$savedKey] = [$current[$savedKey]];
                            }
                            $current[$savedKey][] = $savedData;
                        } else {
                            $current[$savedKey] = $savedData;
                        }
                    }
                }
                continue;
            }

            // Match: key = value
            if (preg_match('/^(\w+)\s*=\s*(.+)$/', $trimmed, $m)) {
                $key = $m[1];
                $value = self::parseValue(trim($m[2]));

                if ($nestedData !== null) {
                    $nestedData[$key] = $value;
                } elseif ($current !== null) {
                    $current[$key] = $value;
                }
            }
        }

        return $result;
    }

    // ── Internal ────────────────────────────────────────────────────────

    private static function writeValue(array &$lines, string $key, mixed $value, int $indent): void
    {
        $prefix = str_repeat("    ", $indent);

        if (is_array($value) && !array_is_list($value)) {
            // Nested block
            $lines[] = "{$prefix}{$key} {";
            foreach ($value as $k => $v) {
                self::writeValue($lines, (string) $k, $v, $indent + 1);
            }
            $lines[] = "{$prefix}}";
        } elseif (is_array($value)) {
            // List array — check if items are complex (arrays) or scalar
            $hasComplex = false;
            foreach ($value as $item) {
                if (is_array($item)) { $hasComplex = true; break; }
            }

            if ($hasComplex) {
                // Render each item as a numbered sub-block
                foreach ($value as $i => $item) {
                    if (is_array($item)) {
                        $lines[] = "{$prefix}{$key} {";
                        foreach ($item as $k => $v) {
                            self::writeValue($lines, (string) $k, $v, $indent + 1);
                        }
                        $lines[] = "{$prefix}}";
                    } else {
                        $lines[] = "{$prefix}{$key} = " . self::formatScalar($item);
                    }
                }
            } else {
                // Simple scalar list
                $items = array_map(fn($v) => self::formatScalar($v), $value);
                $lines[] = "{$prefix}{$key} = [" . implode(', ', $items) . "]";
            }
        } elseif (is_bool($value)) {
            $lines[] = "{$prefix}{$key} = " . ($value ? 'true' : 'false');
        } elseif (is_int($value) || is_float($value)) {
            $lines[] = "{$prefix}{$key} = {$value}";
        } elseif (is_null($value)) {
            $lines[] = "{$prefix}{$key} = null";
        } else {
            $escaped = str_replace('"', '\\"', (string) $value);
            $lines[] = "{$prefix}{$key} = \"{$escaped}\"";
        }
    }

    private static function formatScalar(mixed $value): string
    {
        if (is_bool($value)) return $value ? 'true' : 'false';
        if (is_int($value) || is_float($value)) return (string) $value;
        if (is_null($value)) return 'null';
        return '"' . str_replace('"', '\\"', (string) $value) . '"';
    }

    private static function parseValue(string $raw): mixed
    {
        if ($raw === 'true') return true;
        if ($raw === 'false') return false;
        if ($raw === 'null') return null;
        if (ctype_digit($raw) || preg_match('/^-?\d+$/', $raw)) return (int) $raw;
        if (is_numeric($raw)) return (float) $raw;

        // Quoted string
        if (preg_match('/^"(.*)"$/', $raw, $m)) {
            return str_replace('\\"', '"', $m[1]);
        }

        // Array
        if (str_starts_with($raw, '[') && str_ends_with($raw, ']')) {
            $inner = substr($raw, 1, -1);
            if (trim($inner) === '') return [];
            return array_map(fn($v) => self::parseValue(trim($v)), explode(',', $inner));
        }

        return $raw;
    }
}
